services:
  db:
    image: mysql:8.0
    # If you're on Apple Silicon and see weird CPU errors, uncomment the next line:
    # platform: linux/amd64
    command: ["--default-authentication-plugin=mysql_native_password", "--sql-mode="]
    environment:
      MYSQL_DATABASE: news
      MYSQL_USER: news
      MYSQL_PASSWORD: news
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"         # host:container (use 3307 on host to avoid conflicts)
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      APP_ENV: local
      APP_DEBUG: "true"

  web:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE=/api       # build-time value for Vite
    depends_on:
      - api
    ports:
      - "5173:80"  

  scheduler:
    build: ./backend
    working_dir: /app
    command: php artisan schedule:work
    depends_on:
      db:
        condition: service_started
      api:
        condition: service_started
    volumes:
      - ./backend:/app



volumes:
  db_data:

  
